/*
- I wanted to parse www.pokego.org/pokedex/
- I went to https://www.import.io/
- I pasted "http://gokestop.com/info/pokemon-stats-table/" in the box that said "Enter a URL for a
  page with data"
- I got back a CVS and removed and renamed a bunch of columns so that I finally
  had just the columns
    - num
    - name
    - imageUrl
    - pageLink
- I searched for a CVS to JSON converter (I don't need a database because none
  of this data is changing)
  - I found this http://www.csvjson.com/csv2json
*/
// I went to
// just by typing  into)

var POKEDEX = [
  {
    "num": 1,
    "imageUrl": "http://gokestop.com/images/pokedex/bulbasaur-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/bulbasaur/",
    "name": "Bulbasaur",
    "primaryType": "Grass",
    "secondaryType": "Poison",
    "attack": 126,
    "defense": 126,
    "stamina": 90,
    "capturePercentage": "16%",
    "fleePercentage": "10%",
    "weight": "6.9kg",
    "height": "0.7m"
  },
  {
    "num": 2,
    "imageUrl": "http://gokestop.com/images/pokedex/ivysaur-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/ivysaur/",
    "name": "Ivysaur",
    "primaryType": "Grass",
    "secondaryType": "Poison",
    "attack": 156,
    "defense": 158,
    "stamina": 120,
    "capturePercentage": "8%",
    "fleePercentage": "7%",
    "weight": "13.0kg",
    "height": "1.0m"
  },
  {
    "num": 3,
    "imageUrl": "http://gokestop.com/images/pokedex/venusaur-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/venusaur/",
    "name": "Venusaur",
    "primaryType": "Grass",
    "secondaryType": "Poison",
    "attack": 198,
    "defense": 200,
    "stamina": 160,
    "capturePercentage": "4%",
    "fleePercentage": "5%",
    "weight": "100.0kg",
    "height": "2.0m"
  },
  {
    "num": 4,
    "imageUrl": "http://gokestop.com/images/pokedex/charmander-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/charmander/",
    "name": "Charmander",
    "primaryType": "Fire",
    "secondaryType": "",
    "attack": 128,
    "defense": 108,
    "stamina": 78,
    "capturePercentage": "16%",
    "fleePercentage": "10%",
    "weight": "8.5kg",
    "height": "0.6m"
  },
  {
    "num": 5,
    "imageUrl": "http://gokestop.com/images/pokedex/charmeleon-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/charmeleon/",
    "name": "Charmeleon",
    "primaryType": "Fire",
    "secondaryType": "",
    "attack": 160,
    "defense": 140,
    "stamina": 116,
    "capturePercentage": "8%",
    "fleePercentage": "7%",
    "weight": "19.0kg",
    "height": "1.1m"
  },
  {
    "num": 6,
    "imageUrl": "http://gokestop.com/images/pokedex/charizard-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/charizard/",
    "name": "Charizard",
    "primaryType": "Fire",
    "secondaryType": "Flying",
    "attack": 212,
    "defense": 182,
    "stamina": 156,
    "capturePercentage": "4%",
    "fleePercentage": "5%",
    "weight": "90.5kg",
    "height": "1.7m"
  },
  {
    "num": 7,
    "imageUrl": "http://gokestop.com/images/pokedex/squirtle-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/squirtle/",
    "name": "Squirtle",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 112,
    "defense": 142,
    "stamina": 88,
    "capturePercentage": "16%",
    "fleePercentage": "10%",
    "weight": "9.0kg",
    "height": "0.5m"
  },
  {
    "num": 8,
    "imageUrl": "http://gokestop.com/images/pokedex/wartortle-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/wartortle/",
    "name": "Wartortle",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 144,
    "defense": 176,
    "stamina": 118,
    "capturePercentage": "8%",
    "fleePercentage": "7%",
    "weight": "22.5kg",
    "height": "1.0m"
  },
  {
    "num": 9,
    "imageUrl": "http://gokestop.com/images/pokedex/blastoise-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/blastoise/",
    "name": "Blastoise",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 186,
    "defense": 222,
    "stamina": 158,
    "capturePercentage": "4%",
    "fleePercentage": "5%",
    "weight": "85.5kg",
    "height": "1.6m"
  },
  {
    "num": 10,
    "imageUrl": "http://gokestop.com/images/pokedex/caterpie-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/caterpie/",
    "name": "Caterpie",
    "primaryType": "Bug",
    "secondaryType": "",
    "attack": 62,
    "defense": 66,
    "stamina": 90,
    "capturePercentage": "40%",
    "fleePercentage": "20%",
    "weight": "2.9kg",
    "height": "0.3m"
  },
  {
    "num": 11,
    "imageUrl": "http://gokestop.com/images/pokedex/metapod-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/metapod/",
    "name": "Metapod",
    "primaryType": "Bug",
    "secondaryType": "",
    "attack": 56,
    "defense": 86,
    "stamina": 100,
    "capturePercentage": "20%",
    "fleePercentage": "9%",
    "weight": "9.9kg",
    "height": "0.7m"
  },
  {
    "num": 12,
    "imageUrl": "http://gokestop.com/images/pokedex/butterfree-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/butterfree/",
    "name": "Butterfree",
    "primaryType": "Bug",
    "secondaryType": "Flying",
    "attack": 144,
    "defense": 144,
    "stamina": 120,
    "capturePercentage": "10%",
    "fleePercentage": "6%",
    "weight": "32.0kg",
    "height": "1.1m"
  },
  {
    "num": 13,
    "imageUrl": "http://gokestop.com/images/pokedex/weedle-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/weedle/",
    "name": "Weedle",
    "primaryType": "Bug",
    "secondaryType": "Poison",
    "attack": 68,
    "defense": 64,
    "stamina": 80,
    "capturePercentage": "40%",
    "fleePercentage": "20%",
    "weight": "3.2kg",
    "height": "0.3m"
  },
  {
    "num": 14,
    "imageUrl": "http://gokestop.com/images/pokedex/kakuna-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/kakuna/",
    "name": "Kakuna",
    "primaryType": "Bug",
    "secondaryType": "Poison",
    "attack": 62,
    "defense": 82,
    "stamina": 90,
    "capturePercentage": "20%",
    "fleePercentage": "9%",
    "weight": "10.0kg",
    "height": "0.6m"
  },
  {
    "num": 15,
    "imageUrl": "http://gokestop.com/images/pokedex/beedrill-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/beedrill/",
    "name": "Beedrill",
    "primaryType": "Bug",
    "secondaryType": "Poison",
    "attack": 144,
    "defense": 130,
    "stamina": 130,
    "capturePercentage": "10%",
    "fleePercentage": "6%",
    "weight": "29.5kg",
    "height": "1.0m"
  },
  {
    "num": 16,
    "imageUrl": "http://gokestop.com/images/pokedex/pidgey-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/pidgey/",
    "name": "Pidgey",
    "primaryType": "Normal",
    "secondaryType": "Flying",
    "attack": 94,
    "defense": 90,
    "stamina": 80,
    "capturePercentage": "40%",
    "fleePercentage": "20%",
    "weight": "1.8kg",
    "height": "0.3m"
  },
  {
    "num": 17,
    "imageUrl": "http://gokestop.com/images/pokedex/pidgeotto-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/pidgeotto/",
    "name": "Pidgeotto",
    "primaryType": "Normal",
    "secondaryType": "Flying",
    "attack": 126,
    "defense": 122,
    "stamina": 126,
    "capturePercentage": "20%",
    "fleePercentage": "9%",
    "weight": "30.0kg",
    "height": "1.1m"
  },
  {
    "num": 18,
    "imageUrl": "http://gokestop.com/images/pokedex/pidgeot-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/pidgeot/",
    "name": "Pidgeot",
    "primaryType": "Normal",
    "secondaryType": "Flying",
    "attack": 170,
    "defense": 166,
    "stamina": 166,
    "capturePercentage": "10%",
    "fleePercentage": "6%",
    "weight": "39.5kg",
    "height": "1.5m"
  },
  {
    "num": 19,
    "imageUrl": "http://gokestop.com/images/pokedex/rattata-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/rattata/",
    "name": "Rattata",
    "primaryType": "Normal",
    "secondaryType": "",
    "attack": 92,
    "defense": 86,
    "stamina": 60,
    "capturePercentage": "40%",
    "fleePercentage": "20%",
    "weight": "3.5kg",
    "height": "0.3m"
  },
  {
    "num": 20,
    "imageUrl": "http://gokestop.com/images/pokedex/raticate-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/raticate/",
    "name": "Raticate",
    "primaryType": "Normal",
    "secondaryType": "",
    "attack": 146,
    "defense": 150,
    "stamina": 110,
    "capturePercentage": "16%",
    "fleePercentage": "7%",
    "weight": "18.5kg",
    "height": "0.7m"
  },
  {
    "num": 21,
    "imageUrl": "http://gokestop.com/images/pokedex/spearow-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/spearow/",
    "name": "Spearow",
    "primaryType": "Normal",
    "secondaryType": "Flying",
    "attack": 102,
    "defense": 78,
    "stamina": 80,
    "capturePercentage": "40%",
    "fleePercentage": "15%",
    "weight": "2.0kg",
    "height": "0.3m"
  },
  {
    "num": 22,
    "imageUrl": "http://gokestop.com/images/pokedex/fearow-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/fearow/",
    "name": "Fearow",
    "primaryType": "Normal",
    "secondaryType": "Flying",
    "attack": 168,
    "defense": 146,
    "stamina": 130,
    "capturePercentage": "16%",
    "fleePercentage": "7%",
    "weight": "38.0kg",
    "height": "1.2m"
  },
  {
    "num": 23,
    "imageUrl": "http://gokestop.com/images/pokedex/ekans-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/ekans/",
    "name": "Ekans",
    "primaryType": "Poison",
    "secondaryType": "",
    "attack": 112,
    "defense": 112,
    "stamina": 70,
    "capturePercentage": "40%",
    "fleePercentage": "15%",
    "weight": "6.9kg",
    "height": "2.0m"
  },
  {
    "num": 24,
    "imageUrl": "http://gokestop.com/images/pokedex/arbok-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/arbok/",
    "name": "Arbok",
    "primaryType": "Poison",
    "secondaryType": "",
    "attack": 166,
    "defense": 166,
    "stamina": 120,
    "capturePercentage": "16%",
    "fleePercentage": "7%",
    "weight": "65.0kg",
    "height": "3.5m"
  },
  {
    "num": 25,
    "imageUrl": "http://gokestop.com/images/pokedex/pikachu-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/pikachu/",
    "name": "Pikachu",
    "primaryType": "Electric",
    "secondaryType": "",
    "attack": 124,
    "defense": 108,
    "stamina": 70,
    "capturePercentage": "16%",
    "fleePercentage": "10%",
    "weight": "6.0kg",
    "height": "0.4m"
  },
  {
    "num": 26,
    "imageUrl": "http://gokestop.com/images/pokedex/raichu-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/raichu/",
    "name": "Raichu",
    "primaryType": "Electric",
    "secondaryType": "",
    "attack": 200,
    "defense": 154,
    "stamina": 120,
    "capturePercentage": "8%",
    "fleePercentage": "6%",
    "weight": "30.0kg",
    "height": "0.8m"
  },
  {
    "num": 27,
    "imageUrl": "http://gokestop.com/images/pokedex/sandshrew-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/sandshrew/",
    "name": "Sandshrew",
    "primaryType": "Ground",
    "secondaryType": "",
    "attack": 90,
    "defense": 114,
    "stamina": 100,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "12.0kg",
    "height": "0.6m"
  },
  {
    "num": 28,
    "imageUrl": "http://gokestop.com/images/pokedex/sandslash-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/sandslash/",
    "name": "Sandslash",
    "primaryType": "Ground",
    "secondaryType": "",
    "attack": 150,
    "defense": 172,
    "stamina": 150,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "29.5kg",
    "height": "1.0m"
  },
  {
    "num": 29,
    "imageUrl": "http://gokestop.com/images/pokedex/nidoran-female-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/nidoran-female/",
    "name": "Nidoran Female",
    "primaryType": "Poison",
    "secondaryType": "",
    "attack": 100,
    "defense": 104,
    "stamina": 110,
    "capturePercentage": "40%",
    "fleePercentage": "15%",
    "weight": "7.0kg",
    "height": "0.4m"
  },
  {
    "num": 30,
    "imageUrl": "http://gokestop.com/images/pokedex/nidorina-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/nidorina/",
    "name": "Nidorina",
    "primaryType": "Poison",
    "secondaryType": "",
    "attack": 132,
    "defense": 136,
    "stamina": 140,
    "capturePercentage": "20%",
    "fleePercentage": "7%",
    "weight": "20.0kg",
    "height": "0.8m"
  },
  {
    "num": 31,
    "imageUrl": "http://gokestop.com/images/pokedex/nidoqueen-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/nidoqueen/",
    "name": "Nidoqueen",
    "primaryType": "Poison",
    "secondaryType": "Ground",
    "attack": 184,
    "defense": 190,
    "stamina": 180,
    "capturePercentage": "10%",
    "fleePercentage": "5%",
    "weight": "60.0kg",
    "height": "1.3m"
  },
  {
    "num": 32,
    "imageUrl": "http://gokestop.com/images/pokedex/nidoran-male-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/nidoran-male/",
    "name": "Nidoran Male",
    "primaryType": "Poison",
    "secondaryType": "",
    "attack": 110,
    "defense": 94,
    "stamina": 92,
    "capturePercentage": "40%",
    "fleePercentage": "15%",
    "weight": "9.0kg",
    "height": "0.5m"
  },
  {
    "num": 33,
    "imageUrl": "http://gokestop.com/images/pokedex/nidorino-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/nidorino/",
    "name": "Nidorino",
    "primaryType": "Poison",
    "secondaryType": "",
    "attack": 142,
    "defense": 128,
    "stamina": 122,
    "capturePercentage": "20%",
    "fleePercentage": "7%",
    "weight": "19.5kg",
    "height": "0.9m"
  },
  {
    "num": 34,
    "imageUrl": "http://gokestop.com/images/pokedex/nidoking-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/nidoking/",
    "name": "Nidoking",
    "primaryType": "Poison",
    "secondaryType": "Ground",
    "attack": 204,
    "defense": 170,
    "stamina": 162,
    "capturePercentage": "10%",
    "fleePercentage": "5%",
    "weight": "62.0kg",
    "height": "1.4m"
  },
  {
    "num": 35,
    "imageUrl": "http://gokestop.com/images/pokedex/clefairy-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/clefairy/",
    "name": "Clefairy",
    "primaryType": "Fairy",
    "secondaryType": "",
    "attack": 116,
    "defense": 124,
    "stamina": 140,
    "capturePercentage": "24%",
    "fleePercentage": "10%",
    "weight": "7.5kg",
    "height": "0.6m"
  },
  {
    "num": 36,
    "imageUrl": "http://gokestop.com/images/pokedex/clefable-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/clefable/",
    "name": "Clefable",
    "primaryType": "Fairy",
    "secondaryType": "",
    "attack": 178,
    "defense": 178,
    "stamina": 190,
    "capturePercentage": "8%",
    "fleePercentage": "6%",
    "weight": "40.0kg",
    "height": "1.3m"
  },
  {
    "num": 37,
    "imageUrl": "http://gokestop.com/images/pokedex/vulpix-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/vulpix/",
    "name": "Vulpix",
    "primaryType": "Fire",
    "secondaryType": "",
    "attack": 106,
    "defense": 118,
    "stamina": 76,
    "capturePercentage": "24%",
    "fleePercentage": "10%",
    "weight": "9.9kg",
    "height": "0.6m"
  },
  {
    "num": 38,
    "imageUrl": "http://gokestop.com/images/pokedex/ninetales-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/ninetales/",
    "name": "Ninetales",
    "primaryType": "Fire",
    "secondaryType": "",
    "attack": 176,
    "defense": 194,
    "stamina": 146,
    "capturePercentage": "8%",
    "fleePercentage": "6%",
    "weight": "19.9kg",
    "height": "1.1m"
  },
  {
    "num": 39,
    "imageUrl": "http://gokestop.com/images/pokedex/jigglypuff-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/jigglypuff/",
    "name": "Jigglypuff",
    "primaryType": "Normal",
    "secondaryType": "Fairy",
    "attack": 98,
    "defense": 54,
    "stamina": 230,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "5.5kg",
    "height": "0.5m"
  },
  {
    "num": 40,
    "imageUrl": "http://gokestop.com/images/pokedex/wigglytuff-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/wigglytuff/",
    "name": "Wigglytuff",
    "primaryType": "Normal",
    "secondaryType": "Fairy",
    "attack": 168,
    "defense": 108,
    "stamina": 280,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "12.0kg",
    "height": "1.0m"
  },
  {
    "num": 41,
    "imageUrl": "http://gokestop.com/images/pokedex/zubat-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/zubat/",
    "name": "Zubat",
    "primaryType": "Poison",
    "secondaryType": "Flying",
    "attack": 88,
    "defense": 90,
    "stamina": 80,
    "capturePercentage": "40%",
    "fleePercentage": "20%",
    "weight": "7.5kg",
    "height": "0.8m"
  },
  {
    "num": 42,
    "imageUrl": "http://gokestop.com/images/pokedex/golbat-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/golbat/",
    "name": "Golbat",
    "primaryType": "Poison",
    "secondaryType": "Flying",
    "attack": 164,
    "defense": 164,
    "stamina": 150,
    "capturePercentage": "16%",
    "fleePercentage": "7%",
    "weight": "55.0kg",
    "height": "1.6m"
  },
  {
    "num": 43,
    "imageUrl": "http://gokestop.com/images/pokedex/oddish-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/oddish/",
    "name": "Oddish",
    "primaryType": "Grass",
    "secondaryType": "Poison",
    "attack": 134,
    "defense": 130,
    "stamina": 90,
    "capturePercentage": "48%",
    "fleePercentage": "15%",
    "weight": "5.4kg",
    "height": "0.5m"
  },
  {
    "num": 44,
    "imageUrl": "http://gokestop.com/images/pokedex/gloom-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/gloom/",
    "name": "Gloom",
    "primaryType": "Grass",
    "secondaryType": "Poison",
    "attack": 162,
    "defense": 158,
    "stamina": 120,
    "capturePercentage": "24%",
    "fleePercentage": "7%",
    "weight": "8.6kg",
    "height": "0.8m"
  },
  {
    "num": 45,
    "imageUrl": "http://gokestop.com/images/pokedex/vileplume-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/vileplume/",
    "name": "Vileplume",
    "primaryType": "Grass",
    "secondaryType": "Poison",
    "attack": 202,
    "defense": 190,
    "stamina": 150,
    "capturePercentage": "12%",
    "fleePercentage": "5%",
    "weight": "18.6kg",
    "height": "1.2m"
  },
  {
    "num": 46,
    "imageUrl": "http://gokestop.com/images/pokedex/paras-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/paras/",
    "name": "Paras",
    "primaryType": "Bug",
    "secondaryType": "Grass",
    "attack": 122,
    "defense": 120,
    "stamina": 70,
    "capturePercentage": "32%",
    "fleePercentage": "15%",
    "weight": "5.4kg",
    "height": "0.3m"
  },
  {
    "num": 47,
    "imageUrl": "http://gokestop.com/images/pokedex/parasect-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/parasect/",
    "name": "Parasect",
    "primaryType": "Bug",
    "secondaryType": "Grass",
    "attack": 162,
    "defense": 170,
    "stamina": 120,
    "capturePercentage": "16%",
    "fleePercentage": "7%",
    "weight": "29.5kg",
    "height": "1.0m"
  },
  {
    "num": 48,
    "imageUrl": "http://gokestop.com/images/pokedex/venonat-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/venonat/",
    "name": "Venonat",
    "primaryType": "Bug",
    "secondaryType": "Poison",
    "attack": 108,
    "defense": 118,
    "stamina": 120,
    "capturePercentage": "40%",
    "fleePercentage": "15%",
    "weight": "30.0kg",
    "height": "1.0m"
  },
  {
    "num": 49,
    "imageUrl": "http://gokestop.com/images/pokedex/venomoth-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/venomoth/",
    "name": "Venomoth",
    "primaryType": "Bug",
    "secondaryType": "Poison",
    "attack": 172,
    "defense": 154,
    "stamina": 140,
    "capturePercentage": "16%",
    "fleePercentage": "7%",
    "weight": "12.5kg",
    "height": "1.5m"
  },
  {
    "num": 50,
    "imageUrl": "http://gokestop.com/images/pokedex/diglett-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/diglett/",
    "name": "Diglett",
    "primaryType": "Ground",
    "secondaryType": "",
    "attack": 108,
    "defense": 86,
    "stamina": 20,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "0.8kg",
    "height": "0.2m"
  },
  {
    "num": 51,
    "imageUrl": "http://gokestop.com/images/pokedex/dugtrio-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/dugtrio/",
    "name": "Dugtrio",
    "primaryType": "Ground",
    "secondaryType": "",
    "attack": 148,
    "defense": 140,
    "stamina": 70,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "33.3kg",
    "height": "0.7m"
  },
  {
    "num": 52,
    "imageUrl": "http://gokestop.com/images/pokedex/meowth-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/meowth/",
    "name": "Meowth",
    "primaryType": "Normal",
    "secondaryType": "",
    "attack": 104,
    "defense": 94,
    "stamina": 80,
    "capturePercentage": "40%",
    "fleePercentage": "15%",
    "weight": "4.2kg",
    "height": "0.4m"
  },
  {
    "num": 53,
    "imageUrl": "http://gokestop.com/images/pokedex/persian-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/persian/",
    "name": "Persian",
    "primaryType": "Normal",
    "secondaryType": "",
    "attack": 156,
    "defense": 146,
    "stamina": 130,
    "capturePercentage": "16%",
    "fleePercentage": "7%",
    "weight": "32.0kg",
    "height": "1.0m"
  },
  {
    "num": 54,
    "imageUrl": "http://gokestop.com/images/pokedex/psyduck-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/psyduck/",
    "name": "Psyduck",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 132,
    "defense": 112,
    "stamina": 100,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "19.6kg",
    "height": "0.8m"
  },
  {
    "num": 55,
    "imageUrl": "http://gokestop.com/images/pokedex/golduck-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/golduck/",
    "name": "Golduck",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 194,
    "defense": 176,
    "stamina": 160,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "76.6kg",
    "height": "1.7m"
  },
  {
    "num": 56,
    "imageUrl": "http://gokestop.com/images/pokedex/mankey-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/mankey/",
    "name": "Mankey",
    "primaryType": "Fighting",
    "secondaryType": "",
    "attack": 122,
    "defense": 96,
    "stamina": 80,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "28.0kg",
    "height": "0.5m"
  },
  {
    "num": 57,
    "imageUrl": "http://gokestop.com/images/pokedex/primeape-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/primeape/",
    "name": "Primeape",
    "primaryType": "Fighting",
    "secondaryType": "",
    "attack": 178,
    "defense": 150,
    "stamina": 130,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "32.0kg",
    "height": "1.0m"
  },
  {
    "num": 58,
    "imageUrl": "http://gokestop.com/images/pokedex/growlithe-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/growlithe/",
    "name": "Growlithe",
    "primaryType": "Fire",
    "secondaryType": "",
    "attack": 156,
    "defense": 110,
    "stamina": 110,
    "capturePercentage": "24%",
    "fleePercentage": "10%",
    "weight": "19.0kg",
    "height": "0.7m"
  },
  {
    "num": 59,
    "imageUrl": "http://gokestop.com/images/pokedex/arcanine-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/arcanine/",
    "name": "Arcanine",
    "primaryType": "Fire",
    "secondaryType": "",
    "attack": 230,
    "defense": 180,
    "stamina": 180,
    "capturePercentage": "8%",
    "fleePercentage": "6%",
    "weight": "155.0kg",
    "height": "1.9m"
  },
  {
    "num": 60,
    "imageUrl": "http://gokestop.com/images/pokedex/poliwag-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/poliwag/",
    "name": "Poliwag",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 108,
    "defense": 98,
    "stamina": 80,
    "capturePercentage": "40%",
    "fleePercentage": "15%",
    "weight": "12.4kg",
    "height": "0.6m"
  },
  {
    "num": 61,
    "imageUrl": "http://gokestop.com/images/pokedex/poliwhirl-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/poliwhirl/",
    "name": "Poliwhirl",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 132,
    "defense": 132,
    "stamina": 130,
    "capturePercentage": "20%",
    "fleePercentage": "7%",
    "weight": "20.0kg",
    "height": "1.0m"
  },
  {
    "num": 62,
    "imageUrl": "http://gokestop.com/images/pokedex/poliwrath-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/poliwrath/",
    "name": "Poliwrath",
    "primaryType": "Water",
    "secondaryType": "Fighting",
    "attack": 180,
    "defense": 202,
    "stamina": 180,
    "capturePercentage": "10%",
    "fleePercentage": "5%",
    "weight": "54.0kg",
    "height": "1.3m"
  },
  {
    "num": 63,
    "imageUrl": "http://gokestop.com/images/pokedex/abra-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/abra/",
    "name": "Abra",
    "primaryType": "Psychic",
    "secondaryType": "",
    "attack": 110,
    "defense": 76,
    "stamina": 50,
    "capturePercentage": "40%",
    "fleePercentage": "99%",
    "weight": "19.5kg",
    "height": "0.9m"
  },
  {
    "num": 64,
    "imageUrl": "http://gokestop.com/images/pokedex/kadabra-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/kadabra/",
    "name": "Kadabra",
    "primaryType": "Psychic",
    "secondaryType": "",
    "attack": 150,
    "defense": 112,
    "stamina": 80,
    "capturePercentage": "20%",
    "fleePercentage": "7%",
    "weight": "56.5kg",
    "height": "1.3m"
  },
  {
    "num": 65,
    "imageUrl": "http://gokestop.com/images/pokedex/alakazam-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/alakazam/",
    "name": "Alakazam",
    "primaryType": "Psychic",
    "secondaryType": "",
    "attack": 186,
    "defense": 152,
    "stamina": 110,
    "capturePercentage": "10%",
    "fleePercentage": "5%",
    "weight": "48.0kg",
    "height": "1.5m"
  },
  {
    "num": 66,
    "imageUrl": "http://gokestop.com/images/pokedex/machop-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/machop/",
    "name": "Machop",
    "primaryType": "Fighting",
    "secondaryType": "",
    "attack": 118,
    "defense": 96,
    "stamina": 140,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "19.5kg",
    "height": "0.8m"
  },
  {
    "num": 67,
    "imageUrl": "http://gokestop.com/images/pokedex/machoke-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/machoke/",
    "name": "Machoke",
    "primaryType": "Fighting",
    "secondaryType": "",
    "attack": 154,
    "defense": 144,
    "stamina": 160,
    "capturePercentage": "20%",
    "fleePercentage": "7%",
    "weight": "70.5kg",
    "height": "1.5m"
  },
  {
    "num": 68,
    "imageUrl": "http://gokestop.com/images/pokedex/machamp-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/machamp/",
    "name": "Machamp",
    "primaryType": "Fighting",
    "secondaryType": "",
    "attack": 198,
    "defense": 180,
    "stamina": 180,
    "capturePercentage": "10%",
    "fleePercentage": "5%",
    "weight": "130.0kg",
    "height": "1.6m"
  },
  {
    "num": 69,
    "imageUrl": "http://gokestop.com/images/pokedex/bellsprout-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/bellsprout/",
    "name": "Bellsprout",
    "primaryType": "Grass",
    "secondaryType": "Poison",
    "attack": 158,
    "defense": 78,
    "stamina": 100,
    "capturePercentage": "40%",
    "fleePercentage": "15%",
    "weight": "4.0kg",
    "height": "0.7m"
  },
  {
    "num": 70,
    "imageUrl": "http://gokestop.com/images/pokedex/weepinbell-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/weepinbell/",
    "name": "Weepinbell",
    "primaryType": "Grass",
    "secondaryType": "Poison",
    "attack": 190,
    "defense": 110,
    "stamina": 130,
    "capturePercentage": "20%",
    "fleePercentage": "7%",
    "weight": "6.4kg",
    "height": "1.0m"
  },
  {
    "num": 71,
    "imageUrl": "http://gokestop.com/images/pokedex/victreebel-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/victreebel/",
    "name": "Victreebel",
    "primaryType": "Grass",
    "secondaryType": "Poison",
    "attack": 222,
    "defense": 152,
    "stamina": 160,
    "capturePercentage": "10%",
    "fleePercentage": "5%",
    "weight": "15.5kg",
    "height": "1.7m"
  },
  {
    "num": 72,
    "imageUrl": "http://gokestop.com/images/pokedex/tentacool-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/tentacool/",
    "name": "Tentacool",
    "primaryType": "Water",
    "secondaryType": "Poison",
    "attack": 106,
    "defense": 136,
    "stamina": 80,
    "capturePercentage": "40%",
    "fleePercentage": "15%",
    "weight": "45.5kg",
    "height": "0.9m"
  },
  {
    "num": 73,
    "imageUrl": "http://gokestop.com/images/pokedex/tentacruel-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/tentacruel/",
    "name": "Tentacruel",
    "primaryType": "Water",
    "secondaryType": "Poison",
    "attack": 170,
    "defense": 196,
    "stamina": 160,
    "capturePercentage": "16%",
    "fleePercentage": "7%",
    "weight": "55.0kg",
    "height": "1.6m"
  },
  {
    "num": 74,
    "imageUrl": "http://gokestop.com/images/pokedex/geodude-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/geodude/",
    "name": "Geodude",
    "primaryType": "Rock",
    "secondaryType": "Ground",
    "attack": 106,
    "defense": 118,
    "stamina": 80,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "20.0kg",
    "height": "0.4m"
  },
  {
    "num": 75,
    "imageUrl": "http://gokestop.com/images/pokedex/graveler-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/graveler/",
    "name": "Graveler",
    "primaryType": "Rock",
    "secondaryType": "Ground",
    "attack": 142,
    "defense": 156,
    "stamina": 110,
    "capturePercentage": "20%",
    "fleePercentage": "7%",
    "weight": "105.0kg",
    "height": "1.0m"
  },
  {
    "num": 76,
    "imageUrl": "http://gokestop.com/images/pokedex/golem-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/golem/",
    "name": "Golem",
    "primaryType": "Rock",
    "secondaryType": "Ground",
    "attack": 176,
    "defense": 198,
    "stamina": 160,
    "capturePercentage": "10%",
    "fleePercentage": "5%",
    "weight": "300.0kg",
    "height": "1.4m"
  },
  {
    "num": 77,
    "imageUrl": "http://gokestop.com/images/pokedex/ponyta-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/ponyta/",
    "name": "Ponyta",
    "primaryType": "Fire",
    "secondaryType": "",
    "attack": 168,
    "defense": 138,
    "stamina": 100,
    "capturePercentage": "32%",
    "fleePercentage": "10%",
    "weight": "30.0kg",
    "height": "1.0m"
  },
  {
    "num": 78,
    "imageUrl": "http://gokestop.com/images/pokedex/rapidash-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/rapidash/",
    "name": "Rapidash",
    "primaryType": "Fire",
    "secondaryType": "",
    "attack": 200,
    "defense": 170,
    "stamina": 130,
    "capturePercentage": "12%",
    "fleePercentage": "6%",
    "weight": "95.0kg",
    "height": "1.7m"
  },
  {
    "num": 79,
    "imageUrl": "http://gokestop.com/images/pokedex/slowpoke-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/slowpoke/",
    "name": "Slowpoke",
    "primaryType": "Water",
    "secondaryType": "Psychic",
    "attack": 110,
    "defense": 110,
    "stamina": 180,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "36.0kg",
    "height": "1.2m"
  },
  {
    "num": 80,
    "imageUrl": "http://gokestop.com/images/pokedex/slowbro-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/slowbro/",
    "name": "Slowbro",
    "primaryType": "Water",
    "secondaryType": "Psychic",
    "attack": 184,
    "defense": 198,
    "stamina": 190,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "78.5kg",
    "height": "1.6m"
  },
  {
    "num": 81,
    "imageUrl": "http://gokestop.com/images/pokedex/magnemite-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/magnemite/",
    "name": "Magnemite",
    "primaryType": "Electric",
    "secondaryType": "Steel",
    "attack": 128,
    "defense": 138,
    "stamina": 50,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "6.0kg",
    "height": "0.3m"
  },
  {
    "num": 82,
    "imageUrl": "http://gokestop.com/images/pokedex/magneton-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/magneton/",
    "name": "Magneton",
    "primaryType": "Electric",
    "secondaryType": "Steel",
    "attack": 186,
    "defense": 180,
    "stamina": 100,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "60.0kg",
    "height": "1.0m"
  },
  {
    "num": 83,
    "imageUrl": "http://gokestop.com/images/pokedex/farfetch-d-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/farfetch-d/",
    "name": "Farfetched",
    "primaryType": "Normal",
    "secondaryType": "Flying",
    "attack": 138,
    "defense": 132,
    "stamina": 104,
    "capturePercentage": "24%",
    "fleePercentage": "9%",
    "weight": "15.0kg",
    "height": "0.8m"
  },
  {
    "num": 84,
    "imageUrl": "http://gokestop.com/images/pokedex/doduo-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/doduo/",
    "name": "Doduo",
    "primaryType": "Normal",
    "secondaryType": "Flying",
    "attack": 126,
    "defense": 96,
    "stamina": 70,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "39.2kg",
    "height": "1.4m"
  },
  {
    "num": 85,
    "imageUrl": "http://gokestop.com/images/pokedex/dodrio-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/dodrio/",
    "name": "Dodrio",
    "primaryType": "Normal",
    "secondaryType": "Flying",
    "attack": 182,
    "defense": 150,
    "stamina": 120,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "85.2kg",
    "height": "1.8m"
  },
  {
    "num": 86,
    "imageUrl": "http://gokestop.com/images/pokedex/seel-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/seel/",
    "name": "Seel",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 104,
    "defense": 138,
    "stamina": 130,
    "capturePercentage": "40%",
    "fleePercentage": "9%",
    "weight": "90.0kg",
    "height": "1.1m"
  },
  {
    "num": 87,
    "imageUrl": "http://gokestop.com/images/pokedex/dewgong-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/dewgong/",
    "name": "Dewgong",
    "primaryType": "Water",
    "secondaryType": "Ice",
    "attack": 156,
    "defense": 192,
    "stamina": 180,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "120.0kg",
    "height": "1.7m"
  },
  {
    "num": 88,
    "imageUrl": "http://gokestop.com/images/pokedex/grimer-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/grimer/",
    "name": "Grimer",
    "primaryType": "Poison",
    "secondaryType": "",
    "attack": 124,
    "defense": 110,
    "stamina": 160,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "30.0kg",
    "height": "0.9m"
  },
  {
    "num": 89,
    "imageUrl": "http://gokestop.com/images/pokedex/muk-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/muk/",
    "name": "Muk",
    "primaryType": "Poison",
    "secondaryType": "",
    "attack": 180,
    "defense": 188,
    "stamina": 210,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "30.0kg",
    "height": "1.2m"
  },
  {
    "num": 90,
    "imageUrl": "http://gokestop.com/images/pokedex/shellder-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/shellder/",
    "name": "Shellder",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 120,
    "defense": 112,
    "stamina": 60,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "4.0kg",
    "height": "0.3m"
  },
  {
    "num": 91,
    "imageUrl": "http://gokestop.com/images/pokedex/cloyster-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/cloyster/",
    "name": "Cloyster",
    "primaryType": "Water",
    "secondaryType": "Ice",
    "attack": 196,
    "defense": 196,
    "stamina": 100,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "132.5kg",
    "height": "1.5m"
  },
  {
    "num": 92,
    "imageUrl": "http://gokestop.com/images/pokedex/gastly-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/gastly/",
    "name": "Gastly",
    "primaryType": "Ghost",
    "secondaryType": "Poison",
    "attack": 136,
    "defense": 82,
    "stamina": 60,
    "capturePercentage": "32%",
    "fleePercentage": "10%",
    "weight": "0.1kg",
    "height": "1.3m"
  },
  {
    "num": 93,
    "imageUrl": "http://gokestop.com/images/pokedex/haunter-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/haunter/",
    "name": "Haunter",
    "primaryType": "Ghost",
    "secondaryType": "Poison",
    "attack": 172,
    "defense": 118,
    "stamina": 90,
    "capturePercentage": "16%",
    "fleePercentage": "7%",
    "weight": "0.1kg",
    "height": "1.6m"
  },
  {
    "num": 94,
    "imageUrl": "http://gokestop.com/images/pokedex/gengar-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/gengar/",
    "name": "Gengar",
    "primaryType": "Ghost",
    "secondaryType": "Poison",
    "attack": 204,
    "defense": 156,
    "stamina": 120,
    "capturePercentage": "8%",
    "fleePercentage": "5%",
    "weight": "40.5kg",
    "height": "1.5m"
  },
  {
    "num": 95,
    "imageUrl": "http://gokestop.com/images/pokedex/onix-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/onix/",
    "name": "Onix",
    "primaryType": "Rock",
    "secondaryType": "Ground",
    "attack": 90,
    "defense": 186,
    "stamina": 70,
    "capturePercentage": "16%",
    "fleePercentage": "9%",
    "weight": "210.0kg",
    "height": "8.8m"
  },
  {
    "num": 96,
    "imageUrl": "http://gokestop.com/images/pokedex/drowzee-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/drowzee/",
    "name": "Drowzee",
    "primaryType": "Psychic",
    "secondaryType": "",
    "attack": 104,
    "defense": 140,
    "stamina": 120,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "32.4kg",
    "height": "1.0m"
  },
  {
    "num": 97,
    "imageUrl": "http://gokestop.com/images/pokedex/hypno-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/hypno/",
    "name": "Hypno",
    "primaryType": "Psychic",
    "secondaryType": "",
    "attack": 162,
    "defense": 196,
    "stamina": 170,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "75.6kg",
    "height": "1.6m"
  },
  {
    "num": 98,
    "imageUrl": "http://gokestop.com/images/pokedex/krabby-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/krabby/",
    "name": "Krabby",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 116,
    "defense": 110,
    "stamina": 60,
    "capturePercentage": "40%",
    "fleePercentage": "15%",
    "weight": "6.5kg",
    "height": "0.4m"
  },
  {
    "num": 99,
    "imageUrl": "http://gokestop.com/images/pokedex/kingler-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/kingler/",
    "name": "Kingler",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 178,
    "defense": 168,
    "stamina": 110,
    "capturePercentage": "16%",
    "fleePercentage": "7%",
    "weight": "60.0kg",
    "height": "1.3m"
  },
  {
    "num": 100,
    "imageUrl": "http://gokestop.com/images/pokedex/voltorb-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/voltorb/",
    "name": "Voltorb",
    "primaryType": "Electric",
    "secondaryType": "",
    "attack": 102,
    "defense": 124,
    "stamina": 80,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "10.4kg",
    "height": "0.5m"
  },
  {
    "num": 101,
    "imageUrl": "http://gokestop.com/images/pokedex/electrode-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/electrode/",
    "name": "Electrode",
    "primaryType": "Electric",
    "secondaryType": "",
    "attack": 150,
    "defense": 174,
    "stamina": 120,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "66.6kg",
    "height": "1.2m"
  },
  {
    "num": 102,
    "imageUrl": "http://gokestop.com/images/pokedex/exeggcute-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/exeggcute/",
    "name": "Exeggcute",
    "primaryType": "Grass",
    "secondaryType": "Psychic",
    "attack": 110,
    "defense": 132,
    "stamina": 120,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "2.5kg",
    "height": "0.4m"
  },
  {
    "num": 103,
    "imageUrl": "http://gokestop.com/images/pokedex/exeggutor-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/exeggutor/",
    "name": "Exeggutor",
    "primaryType": "Grass",
    "secondaryType": "Psychic",
    "attack": 232,
    "defense": 164,
    "stamina": 190,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "120.0kg",
    "height": "2.0m"
  },
  {
    "num": 104,
    "imageUrl": "http://gokestop.com/images/pokedex/cubone-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/cubone/",
    "name": "Cubone",
    "primaryType": "Ground",
    "secondaryType": "",
    "attack": 102,
    "defense": 150,
    "stamina": 100,
    "capturePercentage": "32%",
    "fleePercentage": "10%",
    "weight": "6.5kg",
    "height": "0.4m"
  },
  {
    "num": 105,
    "imageUrl": "http://gokestop.com/images/pokedex/marowak-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/marowak/",
    "name": "Marowak",
    "primaryType": "Ground",
    "secondaryType": "",
    "attack": 140,
    "defense": 202,
    "stamina": 120,
    "capturePercentage": "12%",
    "fleePercentage": "6%",
    "weight": "45.0kg",
    "height": "1.0m"
  },
  {
    "num": 106,
    "imageUrl": "http://gokestop.com/images/pokedex/hitmonlee-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/hitmonlee/",
    "name": "Hitmonlee",
    "primaryType": "Fighting",
    "secondaryType": "",
    "attack": 148,
    "defense": 172,
    "stamina": 100,
    "capturePercentage": "16%",
    "fleePercentage": "9%",
    "weight": "49.8kg",
    "height": "1.5m"
  },
  {
    "num": 107,
    "imageUrl": "http://gokestop.com/images/pokedex/hitmonchan-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/hitmonchan/",
    "name": "Hitmonchan",
    "primaryType": "Fighting",
    "secondaryType": "",
    "attack": 138,
    "defense": 204,
    "stamina": 100,
    "capturePercentage": "16%",
    "fleePercentage": "9%",
    "weight": "50.2kg",
    "height": "1.4m"
  },
  {
    "num": 108,
    "imageUrl": "http://gokestop.com/images/pokedex/lickitung-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/lickitung/",
    "name": "Lickitung",
    "primaryType": "Normal",
    "secondaryType": "",
    "attack": 126,
    "defense": 160,
    "stamina": 180,
    "capturePercentage": "16%",
    "fleePercentage": "9%",
    "weight": "65.5kg",
    "height": "1.2m"
  },
  {
    "num": 109,
    "imageUrl": "http://gokestop.com/images/pokedex/koffing-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/koffing/",
    "name": "Koffing",
    "primaryType": "Poison",
    "secondaryType": "",
    "attack": 136,
    "defense": 142,
    "stamina": 80,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "1.0kg",
    "height": "0.6m"
  },
  {
    "num": 110,
    "imageUrl": "http://gokestop.com/images/pokedex/weezing-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/weezing/",
    "name": "Weezing",
    "primaryType": "Poison",
    "secondaryType": "",
    "attack": 190,
    "defense": 198,
    "stamina": 130,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "9.5kg",
    "height": "1.2m"
  },
  {
    "num": 111,
    "imageUrl": "http://gokestop.com/images/pokedex/rhyhorn-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/rhyhorn/",
    "name": "Rhyhorn",
    "primaryType": "Ground",
    "secondaryType": "Rock",
    "attack": 110,
    "defense": 116,
    "stamina": 160,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "115.0kg",
    "height": "1.0m"
  },
  {
    "num": 112,
    "imageUrl": "http://gokestop.com/images/pokedex/rhydon-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/rhydon/",
    "name": "Rhydon",
    "primaryType": "Ground",
    "secondaryType": "Rock",
    "attack": 166,
    "defense": 160,
    "stamina": 210,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "120.0kg",
    "height": "1.9m"
  },
  {
    "num": 113,
    "imageUrl": "http://gokestop.com/images/pokedex/chansey-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/chansey/",
    "name": "Chansey",
    "primaryType": "Normal",
    "secondaryType": "",
    "attack": 40,
    "defense": 60,
    "stamina": 500,
    "capturePercentage": "16%",
    "fleePercentage": "9%",
    "weight": "34.6kg",
    "height": "1.1m"
  },
  {
    "num": 114,
    "imageUrl": "http://gokestop.com/images/pokedex/tangela-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/tangela/",
    "name": "Tangela",
    "primaryType": "Grass",
    "secondaryType": "",
    "attack": 164,
    "defense": 152,
    "stamina": 130,
    "capturePercentage": "32%",
    "fleePercentage": "9%",
    "weight": "35.0kg",
    "height": "1.0m"
  },
  {
    "num": 115,
    "imageUrl": "http://gokestop.com/images/pokedex/kangaskhan-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/kangaskhan/",
    "name": "Kangaskhan",
    "primaryType": "Normal",
    "secondaryType": "",
    "attack": 142,
    "defense": 178,
    "stamina": 210,
    "capturePercentage": "16%",
    "fleePercentage": "9%",
    "weight": "80.0kg",
    "height": "2.2m"
  },
  {
    "num": 116,
    "imageUrl": "http://gokestop.com/images/pokedex/horsea-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/horsea/",
    "name": "Horsea",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 122,
    "defense": 100,
    "stamina": 60,
    "capturePercentage": "40%",
    "fleePercentage": "10%",
    "weight": "8.0kg",
    "height": "0.4m"
  },
  {
    "num": 117,
    "imageUrl": "http://gokestop.com/images/pokedex/seadra-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/seadra/",
    "name": "Seadra",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 176,
    "defense": 150,
    "stamina": 110,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "25.0kg",
    "height": "1.2m"
  },
  {
    "num": 118,
    "imageUrl": "http://gokestop.com/images/pokedex/goldeen-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/goldeen/",
    "name": "Goldeen",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 112,
    "defense": 126,
    "stamina": 90,
    "capturePercentage": "40%",
    "fleePercentage": "15%",
    "weight": "15.0kg",
    "height": "0.6m"
  },
  {
    "num": 119,
    "imageUrl": "http://gokestop.com/images/pokedex/seaking-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/seaking/",
    "name": "Seaking",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 172,
    "defense": 160,
    "stamina": 160,
    "capturePercentage": "16%",
    "fleePercentage": "7%",
    "weight": "39.0kg",
    "height": "1.3m"
  },
  {
    "num": 120,
    "imageUrl": "http://gokestop.com/images/pokedex/staryu-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/staryu/",
    "name": "Staryu",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 130,
    "defense": 128,
    "stamina": 60,
    "capturePercentage": "40%",
    "fleePercentage": "15%",
    "weight": "34.5kg",
    "height": "0.8m"
  },
  {
    "num": 121,
    "imageUrl": "http://gokestop.com/images/pokedex/starmie-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/starmie/",
    "name": "Starmie",
    "primaryType": "Water",
    "secondaryType": "Psychic",
    "attack": 194,
    "defense": 192,
    "stamina": 120,
    "capturePercentage": "16%",
    "fleePercentage": "6%",
    "weight": "80.0kg",
    "height": "1.1m"
  },
  {
    "num": 122,
    "imageUrl": "http://gokestop.com/images/pokedex/mr-mime-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/mr-mime/",
    "name": "Mr. Mime",
    "primaryType": "Psychic",
    "secondaryType": "Fairy",
    "attack": 154,
    "defense": 196,
    "stamina": 80,
    "capturePercentage": "24%",
    "fleePercentage": "9%",
    "weight": "54.5kg",
    "height": "1.3m"
  },
  {
    "num": 123,
    "imageUrl": "http://gokestop.com/images/pokedex/scyther-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/scyther/",
    "name": "Scyther",
    "primaryType": "Bug",
    "secondaryType": "Flying",
    "attack": 176,
    "defense": 180,
    "stamina": 140,
    "capturePercentage": "24%",
    "fleePercentage": "9%",
    "weight": "56.0kg",
    "height": "1.5m"
  },
  {
    "num": 124,
    "imageUrl": "http://gokestop.com/images/pokedex/jynx-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/jynx/",
    "name": "Jynx",
    "primaryType": "Ice",
    "secondaryType": "Psychic",
    "attack": 172,
    "defense": 134,
    "stamina": 130,
    "capturePercentage": "24%",
    "fleePercentage": "9%",
    "weight": "40.6kg",
    "height": "1.4m"
  },
  {
    "num": 125,
    "imageUrl": "http://gokestop.com/images/pokedex/electabuzz-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/electabuzz/",
    "name": "Electabuzz",
    "primaryType": "Electric",
    "secondaryType": "",
    "attack": 198,
    "defense": 160,
    "stamina": 130,
    "capturePercentage": "24%",
    "fleePercentage": "9%",
    "weight": "30.0kg",
    "height": "1.1m"
  },
  {
    "num": 126,
    "imageUrl": "http://gokestop.com/images/pokedex/magmar-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/magmar/",
    "name": "Magmar",
    "primaryType": "Fire",
    "secondaryType": "",
    "attack": 214,
    "defense": 158,
    "stamina": 130,
    "capturePercentage": "24%",
    "fleePercentage": "9%",
    "weight": "44.5kg",
    "height": "1.3m"
  },
  {
    "num": 127,
    "imageUrl": "http://gokestop.com/images/pokedex/pinsir-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/pinsir/",
    "name": "Pinsir",
    "primaryType": "Bug",
    "secondaryType": "",
    "attack": 184,
    "defense": 186,
    "stamina": 130,
    "capturePercentage": "24%",
    "fleePercentage": "9%",
    "weight": "55.0kg",
    "height": "1.5m"
  },
  {
    "num": 128,
    "imageUrl": "http://gokestop.com/images/pokedex/tauros-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/tauros/",
    "name": "Tauros",
    "primaryType": "Normal",
    "secondaryType": "",
    "attack": 148,
    "defense": 184,
    "stamina": 150,
    "capturePercentage": "24%",
    "fleePercentage": "9%",
    "weight": "88.4kg",
    "height": "1.4m"
  },
  {
    "num": 129,
    "imageUrl": "http://gokestop.com/images/pokedex/magikarp-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/magikarp/",
    "name": "Magikarp",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 42,
    "defense": 84,
    "stamina": 40,
    "capturePercentage": "56%",
    "fleePercentage": "15%",
    "weight": "10.0kg",
    "height": "0.9m"
  },
  {
    "num": 130,
    "imageUrl": "http://gokestop.com/images/pokedex/gyarados-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/gyarados/",
    "name": "Gyarados",
    "primaryType": "Water",
    "secondaryType": "Flying",
    "attack": 192,
    "defense": 196,
    "stamina": 190,
    "capturePercentage": "8%",
    "fleePercentage": "7%",
    "weight": "235.0kg",
    "height": "6.5m"
  },
  {
    "num": 131,
    "imageUrl": "http://gokestop.com/images/pokedex/lapras-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/lapras/",
    "name": "Lapras",
    "primaryType": "Water",
    "secondaryType": "Ice",
    "attack": 186,
    "defense": 190,
    "stamina": 260,
    "capturePercentage": "16%",
    "fleePercentage": "9%",
    "weight": "220.0kg",
    "height": "2.5m"
  },
  {
    "num": 132,
    "imageUrl": "http://gokestop.com/images/pokedex/ditto-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/ditto/",
    "name": "Ditto",
    "primaryType": "Normal",
    "secondaryType": "",
    "attack": 110,
    "defense": 110,
    "stamina": 96,
    "capturePercentage": "16%",
    "fleePercentage": "10%",
    "weight": "4.0kg",
    "height": "0.3m"
  },
  {
    "num": 133,
    "imageUrl": "http://gokestop.com/images/pokedex/eevee-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/eevee/",
    "name": "Eevee",
    "primaryType": "Normal",
    "secondaryType": "",
    "attack": 114,
    "defense": 128,
    "stamina": 110,
    "capturePercentage": "32%",
    "fleePercentage": "10%",
    "weight": "6.5kg",
    "height": "0.3m"
  },
  {
    "num": 134,
    "imageUrl": "http://gokestop.com/images/pokedex/vaporeon-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/vaporeon/",
    "name": "Vaporeon",
    "primaryType": "Water",
    "secondaryType": "",
    "attack": 186,
    "defense": 168,
    "stamina": 260,
    "capturePercentage": "12%",
    "fleePercentage": "6%",
    "weight": "29.0kg",
    "height": "1.0m"
  },
  {
    "num": 135,
    "imageUrl": "http://gokestop.com/images/pokedex/jolteon-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/jolteon/",
    "name": "Jolteon",
    "primaryType": "Electric",
    "secondaryType": "",
    "attack": 192,
    "defense": 174,
    "stamina": 130,
    "capturePercentage": "12%",
    "fleePercentage": "6%",
    "weight": "24.5kg",
    "height": "0.8m"
  },
  {
    "num": 136,
    "imageUrl": "http://gokestop.com/images/pokedex/flareon-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/flareon/",
    "name": "Flareon",
    "primaryType": "Fire",
    "secondaryType": "",
    "attack": 238,
    "defense": 178,
    "stamina": 130,
    "capturePercentage": "12%",
    "fleePercentage": "6%",
    "weight": "25.0kg",
    "height": "0.9m"
  },
  {
    "num": 137,
    "imageUrl": "http://gokestop.com/images/pokedex/porygon-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/porygon/",
    "name": "Porygon",
    "primaryType": "Normal",
    "secondaryType": "",
    "attack": 156,
    "defense": 158,
    "stamina": 130,
    "capturePercentage": "32%",
    "fleePercentage": "9%",
    "weight": "36.5kg",
    "height": "0.8m"
  },
  {
    "num": 138,
    "imageUrl": "http://gokestop.com/images/pokedex/omanyte-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/omanyte/",
    "name": "Omanyte",
    "primaryType": "Rock",
    "secondaryType": "Water",
    "attack": 132,
    "defense": 160,
    "stamina": 70,
    "capturePercentage": "32%",
    "fleePercentage": "9%",
    "weight": "7.5kg",
    "height": "0.4m"
  },
  {
    "num": 139,
    "imageUrl": "http://gokestop.com/images/pokedex/omastar-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/omastar/",
    "name": "Omastar",
    "primaryType": "Rock",
    "secondaryType": "Water",
    "attack": 180,
    "defense": 202,
    "stamina": 140,
    "capturePercentage": "12%",
    "fleePercentage": "5%",
    "weight": "35.0kg",
    "height": "1.0m"
  },
  {
    "num": 140,
    "imageUrl": "http://gokestop.com/images/pokedex/kabuto-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/kabuto/",
    "name": "Kabuto",
    "primaryType": "Rock",
    "secondaryType": "Water",
    "attack": 148,
    "defense": 142,
    "stamina": 60,
    "capturePercentage": "32%",
    "fleePercentage": "9%",
    "weight": "11.5kg",
    "height": "0.5m"
  },
  {
    "num": 141,
    "imageUrl": "http://gokestop.com/images/pokedex/kabutops-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/kabutops/",
    "name": "Kabutops",
    "primaryType": "Rock",
    "secondaryType": "Water",
    "attack": 190,
    "defense": 190,
    "stamina": 120,
    "capturePercentage": "12%",
    "fleePercentage": "5%",
    "weight": "40.5kg",
    "height": "1.3m"
  },
  {
    "num": 142,
    "imageUrl": "http://gokestop.com/images/pokedex/aerodactyl-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/aerodactyl/",
    "name": "Aerodactyl",
    "primaryType": "Rock",
    "secondaryType": "Flying",
    "attack": 182,
    "defense": 162,
    "stamina": 160,
    "capturePercentage": "16%",
    "fleePercentage": "9%",
    "weight": "59.0kg",
    "height": "1.8m"
  },
  {
    "num": 143,
    "imageUrl": "http://gokestop.com/images/pokedex/snorlax-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/snorlax/",
    "name": "Snorlax",
    "primaryType": "Normal",
    "secondaryType": "",
    "attack": 180,
    "defense": 180,
    "stamina": 320,
    "capturePercentage": "16%",
    "fleePercentage": "9%",
    "weight": "460.0kg",
    "height": "2.1m"
  },
  {
    "num": 144,
    "imageUrl": "http://gokestop.com/images/pokedex/articuno-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/articuno/",
    "name": "Articuno",
    "primaryType": "Ice",
    "secondaryType": "Flying",
    "attack": 198,
    "defense": 242,
    "stamina": 180,
    "capturePercentage": "0%",
    "fleePercentage": "10%",
    "weight": "55.4kg",
    "height": "1.7m"
  },
  {
    "num": 145,
    "imageUrl": "http://gokestop.com/images/pokedex/zapdos-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/zapdos/",
    "name": "Zapdos",
    "primaryType": "Electric",
    "secondaryType": "Flying",
    "attack": 232,
    "defense": 194,
    "stamina": 180,
    "capturePercentage": "0%",
    "fleePercentage": "10%",
    "weight": "52.6kg",
    "height": "1.6m"
  },
  {
    "num": 146,
    "imageUrl": "http://gokestop.com/images/pokedex/moltres-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/moltres/",
    "name": "Moltres",
    "primaryType": "Fire",
    "secondaryType": "Flying",
    "attack": 242,
    "defense": 194,
    "stamina": 180,
    "capturePercentage": "0%",
    "fleePercentage": "10%",
    "weight": "60.0kg",
    "height": "2.0m"
  },
  {
    "num": 147,
    "imageUrl": "http://gokestop.com/images/pokedex/dratini-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/dratini/",
    "name": "Dratini",
    "primaryType": "Dragon",
    "secondaryType": "",
    "attack": 128,
    "defense": 110,
    "stamina": 82,
    "capturePercentage": "32%",
    "fleePercentage": "9%",
    "weight": "3.3kg",
    "height": "1.8m"
  },
  {
    "num": 148,
    "imageUrl": "http://gokestop.com/images/pokedex/dragonair-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/dragonair/",
    "name": "Dragonair",
    "primaryType": "Dragon",
    "secondaryType": "",
    "attack": 170,
    "defense": 152,
    "stamina": 122,
    "capturePercentage": "8%",
    "fleePercentage": "6%",
    "weight": "16.5kg",
    "height": "4.0m"
  },
  {
    "num": 149,
    "imageUrl": "http://gokestop.com/images/pokedex/dragonite-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/dragonite/",
    "name": "Dragonite",
    "primaryType": "Dragon",
    "secondaryType": "Flying",
    "attack": 250,
    "defense": 212,
    "stamina": 182,
    "capturePercentage": "4%",
    "fleePercentage": "5%",
    "weight": "210.0kg",
    "height": "2.2m"
  },
  {
    "num": 150,
    "imageUrl": "http://gokestop.com/images/pokedex/mewtwo-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/mewtwo/",
    "name": "Mewtwo",
    "primaryType": "Psychic",
    "secondaryType": "",
    "attack": 284,
    "defense": 202,
    "stamina": 212,
    "capturePercentage": "0%",
    "fleePercentage": "10%",
    "weight": "122.0kg",
    "height": "2.0m"
  },
  {
    "num": 151,
    "imageUrl": "http://gokestop.com/images/pokedex/mew-pokemon.png",
    "imageUrl_alt": "",
    "imageUrl_link": "http://gokestop.com/pokedex/mew/",
    "name": "Mew",
    "primaryType": "Psychic",
    "secondaryType": "",
    "attack": 220,
    "defense": 220,
    "stamina": 200,
    "capturePercentage": "0%",
    "fleePercentage": "10%",
    "weight": "4.0kg",
    "height": "0.4m"
  }
]
