wget http://gokestop.com/images/pokedex/bulbasaur-pokemon.png -O bulbasaur.png
wget http://gokestop.com/images/pokedex/ivysaur-pokemon.png -O ivysaur.png
wget http://gokestop.com/images/pokedex/venusaur-pokemon.png -O venusaur.png
wget http://gokestop.com/images/pokedex/charmander-pokemon.png -O charmander.png
wget http://gokestop.com/images/pokedex/charmeleon-pokemon.png -O charmeleon.png
wget http://gokestop.com/images/pokedex/charizard-pokemon.png -O charizard.png
wget http://gokestop.com/images/pokedex/squirtle-pokemon.png -O squirtle.png
wget http://gokestop.com/images/pokedex/wartortle-pokemon.png -O wartortle.png
wget http://gokestop.com/images/pokedex/blastoise-pokemon.png -O blastoise.png
wget http://gokestop.com/images/pokedex/caterpie-pokemon.png -O caterpie.png
wget http://gokestop.com/images/pokedex/metapod-pokemon.png -O metapod.png
wget http://gokestop.com/images/pokedex/butterfree-pokemon.png -O butterfree.png
wget http://gokestop.com/images/pokedex/weedle-pokemon.png -O weedle.png
wget http://gokestop.com/images/pokedex/kakuna-pokemon.png -O kakuna.png
wget http://gokestop.com/images/pokedex/beedrill-pokemon.png -O beedrill.png
wget http://gokestop.com/images/pokedex/pidgey-pokemon.png -O pidgey.png
wget http://gokestop.com/images/pokedex/pidgeotto-pokemon.png -O pidgeotto.png
wget http://gokestop.com/images/pokedex/pidgeot-pokemon.png -O pidgeot.png
wget http://gokestop.com/images/pokedex/rattata-pokemon.png -O rattata.png
wget http://gokestop.com/images/pokedex/raticate-pokemon.png -O raticate.png
wget http://gokestop.com/images/pokedex/spearow-pokemon.png -O spearow.png
wget http://gokestop.com/images/pokedex/fearow-pokemon.png -O fearow.png
wget http://gokestop.com/images/pokedex/ekans-pokemon.png -O ekans.png
wget http://gokestop.com/images/pokedex/arbok-pokemon.png -O arbok.png
wget http://gokestop.com/images/pokedex/pikachu-pokemon.png -O pikachu.png
wget http://gokestop.com/images/pokedex/raichu-pokemon.png -O raichu.png
wget http://gokestop.com/images/pokedex/sandshrew-pokemon.png -O sandshrew.png
wget http://gokestop.com/images/pokedex/sandslash-pokemon.png -O sandslash.png
wget http://gokestop.com/images/pokedex/nidoran-female-pokemon.png -O nidoran-female.png
wget http://gokestop.com/images/pokedex/nidorina-pokemon.png -O nidorina.png
wget http://gokestop.com/images/pokedex/nidoqueen-pokemon.png -O nidoqueen.png
wget http://gokestop.com/images/pokedex/nidoran-male-pokemon.png -O nidoran-male.png
wget http://gokestop.com/images/pokedex/nidorino-pokemon.png -O nidorino.png
wget http://gokestop.com/images/pokedex/nidoking-pokemon.png -O nidoking.png
wget http://gokestop.com/images/pokedex/clefairy-pokemon.png -O clefairy.png
wget http://gokestop.com/images/pokedex/clefable-pokemon.png -O clefable.png
wget http://gokestop.com/images/pokedex/vulpix-pokemon.png -O vulpix.png
wget http://gokestop.com/images/pokedex/ninetales-pokemon.png -O ninetales.png
wget http://gokestop.com/images/pokedex/jigglypuff-pokemon.png -O jigglypuff.png
wget http://gokestop.com/images/pokedex/wigglytuff-pokemon.png -O wigglytuff.png
wget http://gokestop.com/images/pokedex/zubat-pokemon.png -O zubat.png
wget http://gokestop.com/images/pokedex/golbat-pokemon.png -O golbat.png
wget http://gokestop.com/images/pokedex/oddish-pokemon.png -O oddish.png
wget http://gokestop.com/images/pokedex/gloom-pokemon.png -O gloom.png
wget http://gokestop.com/images/pokedex/vileplume-pokemon.png -O vileplume.png
wget http://gokestop.com/images/pokedex/paras-pokemon.png -O paras.png
wget http://gokestop.com/images/pokedex/parasect-pokemon.png -O parasect.png
wget http://gokestop.com/images/pokedex/venonat-pokemon.png -O venonat.png
wget http://gokestop.com/images/pokedex/venomoth-pokemon.png -O venomoth.png
wget http://gokestop.com/images/pokedex/diglett-pokemon.png -O diglett.png
wget http://gokestop.com/images/pokedex/dugtrio-pokemon.png -O dugtrio.png
wget http://gokestop.com/images/pokedex/meowth-pokemon.png -O meowth.png
wget http://gokestop.com/images/pokedex/persian-pokemon.png -O persian.png
wget http://gokestop.com/images/pokedex/psyduck-pokemon.png -O psyduck.png
wget http://gokestop.com/images/pokedex/golduck-pokemon.png -O golduck.png
wget http://gokestop.com/images/pokedex/mankey-pokemon.png -O mankey.png
wget http://gokestop.com/images/pokedex/primeape-pokemon.png -O primeape.png
wget http://gokestop.com/images/pokedex/growlithe-pokemon.png -O growlithe.png
wget http://gokestop.com/images/pokedex/arcanine-pokemon.png -O arcanine.png
wget http://gokestop.com/images/pokedex/poliwag-pokemon.png -O poliwag.png
wget http://gokestop.com/images/pokedex/poliwhirl-pokemon.png -O poliwhirl.png
wget http://gokestop.com/images/pokedex/poliwrath-pokemon.png -O poliwrath.png
wget http://gokestop.com/images/pokedex/abra-pokemon.png -O abra.png
wget http://gokestop.com/images/pokedex/kadabra-pokemon.png -O kadabra.png
wget http://gokestop.com/images/pokedex/alakazam-pokemon.png -O alakazam.png
wget http://gokestop.com/images/pokedex/machop-pokemon.png -O machop.png
wget http://gokestop.com/images/pokedex/machoke-pokemon.png -O machoke.png
wget http://gokestop.com/images/pokedex/machamp-pokemon.png -O machamp.png
wget http://gokestop.com/images/pokedex/bellsprout-pokemon.png -O bellsprout.png
wget http://gokestop.com/images/pokedex/weepinbell-pokemon.png -O weepinbell.png
wget http://gokestop.com/images/pokedex/victreebel-pokemon.png -O victreebel.png
wget http://gokestop.com/images/pokedex/tentacool-pokemon.png -O tentacool.png
wget http://gokestop.com/images/pokedex/tentacruel-pokemon.png -O tentacruel.png
wget http://gokestop.com/images/pokedex/geodude-pokemon.png -O geodude.png
wget http://gokestop.com/images/pokedex/graveler-pokemon.png -O graveler.png
wget http://gokestop.com/images/pokedex/golem-pokemon.png -O golem.png
wget http://gokestop.com/images/pokedex/ponyta-pokemon.png -O ponyta.png
wget http://gokestop.com/images/pokedex/rapidash-pokemon.png -O rapidash.png
wget http://gokestop.com/images/pokedex/slowpoke-pokemon.png -O slowpoke.png
wget http://gokestop.com/images/pokedex/slowbro-pokemon.png -O slowbro.png
wget http://gokestop.com/images/pokedex/magnemite-pokemon.png -O magnemite.png
wget http://gokestop.com/images/pokedex/magneton-pokemon.png -O magneton.png
wget http://gokestop.com/images/pokedex/farfetch-d-pokemon.png -O farfetch-d.png
wget http://gokestop.com/images/pokedex/doduo-pokemon.png -O doduo.png
wget http://gokestop.com/images/pokedex/dodrio-pokemon.png -O dodrio.png
wget http://gokestop.com/images/pokedex/seel-pokemon.png -O seel.png
wget http://gokestop.com/images/pokedex/dewgong-pokemon.png -O dewgong.png
wget http://gokestop.com/images/pokedex/grimer-pokemon.png -O grimer.png
wget http://gokestop.com/images/pokedex/muk-pokemon.png -O muk.png
wget http://gokestop.com/images/pokedex/shellder-pokemon.png -O shellder.png
wget http://gokestop.com/images/pokedex/cloyster-pokemon.png -O cloyster.png
wget http://gokestop.com/images/pokedex/gastly-pokemon.png -O gastly.png
wget http://gokestop.com/images/pokedex/haunter-pokemon.png -O haunter.png
wget http://gokestop.com/images/pokedex/gengar-pokemon.png -O gengar.png
wget http://gokestop.com/images/pokedex/onix-pokemon.png -O onix.png
wget http://gokestop.com/images/pokedex/drowzee-pokemon.png -O drowzee.png
wget http://gokestop.com/images/pokedex/hypno-pokemon.png -O hypno.png
wget http://gokestop.com/images/pokedex/krabby-pokemon.png -O krabby.png
wget http://gokestop.com/images/pokedex/kingler-pokemon.png -O kingler.png
wget http://gokestop.com/images/pokedex/voltorb-pokemon.png -O voltorb.png
wget http://gokestop.com/images/pokedex/electrode-pokemon.png -O electrode.png
wget http://gokestop.com/images/pokedex/exeggcute-pokemon.png -O exeggcute.png
wget http://gokestop.com/images/pokedex/exeggutor-pokemon.png -O exeggutor.png
wget http://gokestop.com/images/pokedex/cubone-pokemon.png -O cubone.png
wget http://gokestop.com/images/pokedex/marowak-pokemon.png -O marowak.png
wget http://gokestop.com/images/pokedex/hitmonlee-pokemon.png -O hitmonlee.png
wget http://gokestop.com/images/pokedex/hitmonchan-pokemon.png -O hitmonchan.png
wget http://gokestop.com/images/pokedex/lickitung-pokemon.png -O lickitung.png
wget http://gokestop.com/images/pokedex/koffing-pokemon.png -O koffing.png
wget http://gokestop.com/images/pokedex/weezing-pokemon.png -O weezing.png
wget http://gokestop.com/images/pokedex/rhyhorn-pokemon.png -O rhyhorn.png
wget http://gokestop.com/images/pokedex/rhydon-pokemon.png -O rhydon.png
wget http://gokestop.com/images/pokedex/chansey-pokemon.png -O chansey.png
wget http://gokestop.com/images/pokedex/tangela-pokemon.png -O tangela.png
wget http://gokestop.com/images/pokedex/kangaskhan-pokemon.png -O kangaskhan.png
wget http://gokestop.com/images/pokedex/horsea-pokemon.png -O horsea.png
wget http://gokestop.com/images/pokedex/seadra-pokemon.png -O seadra.png
wget http://gokestop.com/images/pokedex/goldeen-pokemon.png -O goldeen.png
wget http://gokestop.com/images/pokedex/seaking-pokemon.png -O seaking.png
wget http://gokestop.com/images/pokedex/staryu-pokemon.png -O staryu.png
wget http://gokestop.com/images/pokedex/starmie-pokemon.png -O starmie.png
wget http://gokestop.com/images/pokedex/mr-mime-pokemon.png -O mr-mime.png
wget http://gokestop.com/images/pokedex/scyther-pokemon.png -O scyther.png
wget http://gokestop.com/images/pokedex/jynx-pokemon.png -O jynx.png
wget http://gokestop.com/images/pokedex/electabuzz-pokemon.png -O electabuzz.png
wget http://gokestop.com/images/pokedex/magmar-pokemon.png -O magmar.png
wget http://gokestop.com/images/pokedex/pinsir-pokemon.png -O pinsir.png
wget http://gokestop.com/images/pokedex/tauros-pokemon.png -O tauros.png
wget http://gokestop.com/images/pokedex/magikarp-pokemon.png -O magikarp.png
wget http://gokestop.com/images/pokedex/gyarados-pokemon.png -O gyarados.png
wget http://gokestop.com/images/pokedex/lapras-pokemon.png -O lapras.png
wget http://gokestop.com/images/pokedex/ditto-pokemon.png -O ditto.png
wget http://gokestop.com/images/pokedex/eevee-pokemon.png -O eevee.png
wget http://gokestop.com/images/pokedex/vaporeon-pokemon.png -O vaporeon.png
wget http://gokestop.com/images/pokedex/jolteon-pokemon.png -O jolteon.png
wget http://gokestop.com/images/pokedex/flareon-pokemon.png -O flareon.png
wget http://gokestop.com/images/pokedex/porygon-pokemon.png -O porygon.png
wget http://gokestop.com/images/pokedex/omanyte-pokemon.png -O omanyte.png
wget http://gokestop.com/images/pokedex/omastar-pokemon.png -O omastar.png
wget http://gokestop.com/images/pokedex/kabuto-pokemon.png -O kabuto.png
wget http://gokestop.com/images/pokedex/kabutops-pokemon.png -O kabutops.png
wget http://gokestop.com/images/pokedex/aerodactyl-pokemon.png -O aerodactyl.png
wget http://gokestop.com/images/pokedex/snorlax-pokemon.png -O snorlax.png
wget http://gokestop.com/images/pokedex/articuno-pokemon.png -O articuno.png
wget http://gokestop.com/images/pokedex/zapdos-pokemon.png -O zapdos.png
wget http://gokestop.com/images/pokedex/moltres-pokemon.png -O moltres.png
wget http://gokestop.com/images/pokedex/dratini-pokemon.png -O dratini.png
wget http://gokestop.com/images/pokedex/dragonair-pokemon.png -O dragonair.png
wget http://gokestop.com/images/pokedex/dragonite-pokemon.png -O dragonite.png
wget http://gokestop.com/images/pokedex/mewtwo-pokemon.png -O mewtwo.png
wget http://gokestop.com/images/pokedex/mew-pokemon.png -O mew.png
